version: '3'

networks:
  overlay:
    external:
      name: pg_cluster_network

volumes:
  pg_access_node_data:
    driver: local
  pg_data_node_1_data:
    driver: local
  pg_data_node_2_data:
    driver: local

services:
  pg_access_node:
    image: timescale/timescaledb-ha:pg15.4-ts2.12.1-all
    container_name: pg_access_node
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - overlay
    volumes:
      - pg_access_node_data:/home/postgres/pgdata/data
      - ./trust-all.sh:/docker-entrypoint-initdb.d/777_trust.sh
      - ./unsafe-boost.sh:/docker-entrypoint-initdb.d/888_boost.sh
      - ./init-access-node.sh:/docker-entrypoint-initdb.d/999_cluster.sh
      - ./data:/tmp/data

  pg_data_node_1:
    image: timescale/timescaledb-ha:pg15.4-ts2.12.1-all
    container_name: pg_data_node_1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    networks:
      - overlay
    volumes:
      - pg_data_node_1_data:/home/postgres/pgdata/data
      - ./trust-all.sh:/docker-entrypoint-initdb.d/777_trust.sh
      - ./unsafe-boost.sh:/docker-entrypoint-initdb.d/888_boost.sh
      - ./init-data-node.sh:/docker-entrypoint-initdb.d/999_cluster.sh

  pg_data_node_2:
    image: timescale/timescaledb-ha:pg15.4-ts2.12.1-all
    container_name: pg_data_node_2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    networks:
      - overlay
    volumes:
      - pg_data_node_2_data:/home/postgres/pgdata/data
      - ./trust-all.sh:/docker-entrypoint-initdb.d/777_trust.sh
      - ./unsafe-boost.sh:/docker-entrypoint-initdb.d/888_boost.sh
      - ./init-data-node.sh:/docker-entrypoint-initdb.d/999_cluster.sh

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '15432:80'
    networks:
      - overlay
