{
 "title": "TimescaleDB",
 "time": { "from": "2019-09-01T21:00:00.000Z", "to": "2019-09-06T20:59:59.000Z" },
 "panels": [
  {
   "title": "Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT time,\n       imei,\n       speed,\n       latitude,\n       longitude\nFROM telemetries\nWHERE $__timeFilter(time)\nGROUP BY time, imei\nORDER BY time\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Speed by vehicles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  imei,\n  speed\nFROM telemetries\nWHERE\n  $__timeFilter(time)\nGROUP BY time, imei\nORDER BY time\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Max speed in 1 hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1h', time) as \"time\",\n  max(speed) as \"speed\"\nFROM telemetries\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY time\nORDER BY time\nLIMIT 100000"
    }
   ]
  }
 ]
}